<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	<NuGetAudit>false</NuGetAudit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="dotenv.net" Version="4.0.2" />
	  <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.19.0" />
	  <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Hangfire" Version="1.8.24" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.24" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="MaxMind.GeoIP2" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Minio" Version="7.0.0" />
    <PackageReference Include="Quartz" Version="3.18.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.1" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
    <PackageReference Include="UAParser" Version="3.1.47" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SNS.Application\SNS.Application.csproj" />
    <ProjectReference Include="..\SNS.Shared\SNS.Shared.csproj" />
    <ProjectReference Include="..\SNS.Domain\SNS.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
	  <None Update="Shared\Resources\DataBases\GeoLite2-City.mmdb">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Always</CopyToPublishDirectory>
	  </None>
	  <None Update="Shared\Resources\Firebase\service-account.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Always</CopyToPublishDirectory>
	  </None>
  </ItemGroup>

	<ItemGroup>
		<None Update="Shared\Resources\MessagingTemplates\Email\Arabic\*.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="Shared\Resources\MessagingTemplates\Email\English\*.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
	</ItemGroup>
</Project>
