namespace SNS.Application.DTOs.Authentication.Account.Requests;

/// <summary>
/// Represents a data transfer object used to
/// finalize a support-initiated phone number change.
/// 
/// This DTO is designed to transfer data between
/// the client and the application layer, validating the code
/// generated by the support action.
/// 
/// It is typically used when a user clicks a magic link or enters a code provided by support.
/// </summary>
public class VerifySupportPhoneChangeDto
{
    /// <summary>
    /// Gets or sets the unique identifier of the pending update context.
    /// </summary>
    public Guid PendingUpdateId { get; set; }

    /// <summary>
    /// Gets or sets the unique identifier of the user.
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Gets or sets the new phone number being verified.
    /// </summary>
    public string PhoneNumber { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the verification code.
    /// 
    /// This value is used to authorize the administrative override.
    /// </summary>
    public string Code { get; set; } = string.Empty;
}